### ISSUE TITLE
Consider yanking twine 5.1.0

### ISSUE THREAD

**Issue by moorepants** [conda-forge/twine-feedstock#57]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Twine 5.1.0 was yanked from PyPi: 

https://pypi.org/project/twine/#history

due to a bug that makes it unusable. I sometimes still get twine 5.1.0 in a conda environment. Can 5.1.0 be yanked from anaconda.org to mirror the PyPi decision?

### Installed packages

NA

### Environment info

NA

**Comment by bollwyvl** [comment]
Oops, this kinda slipped through my attention span: started process on https://github.com/conda-forge/admin-requests/pull/1112

**Comment by bollwyvl** [comment]
https://anaconda.org/conda-forge/twine/files?version=5.1.0 is now in `broken`, but still `main`... watching...

**Comment by bollwyvl** [comment]
Ah, apparently it will _stay_ in `main`, but the solvers will now not find it (without an explicit pin):

```
mamba create --name TEST twine=5.1.0 --dry-run

Looking for: ['twine=5.1.0']

conda-forge/linux-64                                39.2MB @  44.7MB/s  1.1s
conda-forge/noarch                                  16.9MB @  14.4MB/s  1.2s
Could not solve for environment specs
The following package could not be installed
└─ twine 5.1.0**  does not exist (perhaps a typo or a missing channel).
```
or
```
conda create --name TEST twine=5.1.0 --dry-run
Retrieving notices: ...working... done
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - twine=5.1.0*

Current channels:

  - https://conda.anaconda.org/conda-forge
```

`defaults` never shipped that version (not that we could do anything about it), so I don't think there's anything else we can do here. thanks for the report!

**Comment by moorepants** [comment]
Thank you!
